config-version: 2

name: "sst_jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

# dbt-cloud:
#   project-id: 275557 # Put your project id here

profile: sst_jaffle_shop

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  sst_jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  sst_jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
